[build]
builder = "NIXPACKS"

[deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[services.api]
source = "api"
buildCommand = "uv sync --frozen && uv run prisma generate"
startCommand = "uv run uvicorn main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/api/v1/health/"
healthcheckTimeout = 300

[services.api.variables]
PORT = "8000"
PYTHONDONTWRITEBYTECODE = "1"
PYTHONUNBUFFERED = "1"

[services.web]
source = "web"
buildCommand = "npm ci && npx prisma generate && npm run build"
startCommand = "npm start"

[services.web.variables]
PORT = "3000"
NODE_ENV = "production"
NEXT_PUBLIC_API_URL = "${{api.RAILWAY_PUBLIC_DOMAIN}}"

[services.celery-worker]
source = "api"
buildCommand = "uv sync --frozen && uv run prisma generate"
startCommand = "uv run celery -A app.tasks.celery_app worker --loglevel=info"

[services.celery-worker.variables]
PYTHONDONTWRITEBYTECODE = "1"
PYTHONUNBUFFERED = "1"
C_FORCE_ROOT = "1"

[environments.production.variables]
DATABASE_URL = "${{Postgres.DATABASE_URL}}"
DIRECT_URL = "${{Postgres.DATABASE_URL}}"
REDIS_URL = "${{Redis.REDIS_URL}}"
SUPABASE_URL = "${{SUPABASE_URL}}"
SUPABASE_ANON_KEY = "${{SUPABASE_ANON_KEY}}"
SUPABASE_KEY = "${{SUPABASE_KEY}}"
OPENAI_API_KEY = "${{OPENAI_API_KEY}}"
NEXTAUTH_SECRET = "${{NEXTAUTH_SECRET}}"
NEXTAUTH_URL = "${{web.RAILWAY_PUBLIC_DOMAIN}}"
GITHUB_CLIENT_ID = "${{GITHUB_CLIENT_ID}}"
GITHUB_CLIENT_SECRET = "${{GITHUB_CLIENT_SECRET}}"
NEXT_PUBLIC_SUPABASE_URL = "${{SUPABASE_URL}}"
NEXT_PUBLIC_SUPABASE_ANON_KEY = "${{SUPABASE_ANON_KEY}}" 